### ISSUE TITLE
First Aid blurr is transfered to other units in SP mode

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#221]
1. Play SP mode (like editor)
2. Get shot and wait for the blurry view
3. switch to another unit in your team
4. you still have the blurred view although the switched unit is not down

**Comment by sxp2high** [comment]
Fixed (as good as possible for now) for next build.
- It might take up to 10 sec. for the visual effects to disappear (Current loop has to end).
- If switching back to the unconscious unit, the visual effects will not be restarted. (Would be out of sync)

However, unit switch is not really supported, there might be some other issues with it. It's a lot of extra programing work and a lot of data would have to be stored.
Unit switch shouldn't even be possible because of the user input being blocked. (I had to use debug console and selectPlayer to reproduce)

**Comment by Legislator** [comment]
When will be the next update?
